export default {
  DEFAULT_LOCATION_KEY: '215854',
  DEFAULT_LOCATION_STRING: 'Tel Aviv',
  NOTIFICATION_DURATION_SHORT: 4,
  NOTIFICATION_DURATION_MEDIUM: 6,
  NOTIFICATION_DURATION_LONG: 8,
  DEBOUNCE_TIMER_MS: 1000
};
